name: Build and publish a Docker image

on:
  push:
    branches:
      - 'cicd'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          registry: 'https://index.docker.io/v1/'
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            humancorridorconsult/cloudimage:latest
            humancorridorconsult/cloudimage:${{ github.sha }}
